services:
  triage-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${TRIAGE_APP_PORT:-8082}:80"
    environment:
      # Add any environment variables needed for triage-app here
      TZ: ${TZ:-America/Sao_Paulo}
